global:
  acme:
    domain: steadops.local.steadforce.com
  istio:
    ingressGateway:
      namespace: istio-ingress
      
subDomain: trino

trino:
  image:
    tag: 440
  server:
    workers: 1
  additionalCatalogs:
    kafka: |-
      connector.name=kafka
      kafka.nodes=kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
      kafka.table-names=steadforce.tools
      kafka.hide-internal-columns=false
    iceberg: |-
      connector.name=iceberg
      iceberg.catalog.type=nessie
      iceberg.nessie-catalog.uri=http://nessie.nessie.svc.cluster.local:19120/api/v1
      iceberg.nessie-catalog.default-warehouse-dir=s3://steadops-playground-bucket
      iceberg.nessie-catalog.ref=main
      iceberg.register-table-procedure.enabled=true
      iceberg.file-format=PARQUET
      iceberg.unique-table-location=false
      fs.native-s3.enabled=true
      s3.endpoint=http://minio.minio.svc.cluster.local:80
      s3.aws-access-key=${ENV:MINIO_ACCESS_KEY}
      s3.aws-secret-key=${ENV:MINIO_SECRET_KEY}
      s3.region=us-east-1
  env:
    - name: MINIO_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-cred-secret-mirror
          key: accesskey
    - name: MINIO_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: minio-cred-secret-mirror
          key: secretkey