trino:
  coordinator:
    config:
      query:
        # must be lower than the coordinator's jvm heap
        maxMemoryPerNode: 512MB
    jvm:
      # must be lower than the coordinator's memory limit
      maxHeapSize: 1G
    resources:
      limits:
        cpu: 0m
        memory: 1536Mi
      requests: ~
  worker:
    config:
      query:
        # must be lower than the worker's jvm heap
        maxMemoryPerNode: 512MB
    jvm:
      # must be lower than the coordinator's memory limit
      # maxMemoryPerNode + heapHeadroomPerNode
      maxHeapSize: 1G
    resources:
      limits:
        cpu: 0m
        memory: 1536Mi
      requests: ~
