global:
  acme:
    domain: steadops.local.steadforce.com
  istio:
    ingressGateway:
      namespace: istio-ingress
      
subDomain: trino

trino:
  resources:
    limits: 
      cpu: 200m
      memory: 250Mi
    requests:
      cpu: 100m
      memory: 125Mi
  livenessProbe: 
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  additionalCatalogs:
    kafka: |-
      connector.name=kafka
      kafka.nodes=kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
      kafka.table-names=tools
      kafka.hide-internal-columns=false