global:
  acme:
    domain: steadops.local.steadforce.com
  istio:
    ingressGateway:
      namespace: istio-ingress
      
subDomain: trino

trino:
  image:
    tag: 439
  resources:
    limits: 
      cpu: 200m
      memory: 250Mi
    requests:
      cpu: 100m
      memory: 125Mi
  livenessProbe: 
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  additionalCatalogs:
    kafka: |-
      connector.name=kafka
      kafka.nodes=kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
      kafka.table-names=steadforce.tools
      kafka.hide-internal-columns=false
    iceberg: |-
      connector.name=iceberg
      iceberg.catalog.type=nessie
      iceberg.nessie-catalog.uri=http://nessie.nessie.svc.cluster.local:19120/api/v1
      iceberg.nessie-catalog.default-warehouse-dir=s3a://nessie
      s3.path-style-access=true
      s3.endpoint=http://minio.minio.svc.cluster.local:9000
      s3.aws-access-key=${ENV:MINIO_ACCESS_KEY}
      s3.aws-secret-key=${ENV:MINIO_SECRET_KEY}
      iceberg.file-format=PARQUET
  env:
    - name: MINIO_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-cred-secret-mirror
          key: accesskey
    - name: MINIO_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: minio-cred-secret-mirror
          key: secretkey