global:
  acme:
    domain: steadops.local.steadforce.com
  istio:
    ingressGateway:
      namespace: istio-ingress
      
subDomain: trino

trino:
  image:
    tag: 432
  server:
    resources:
      limits: 
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 100m
        memory: 125Mi
    livenessProbe: 
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
    readinessProbe:
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
  worker:
    resources:
      limits: 
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 100m
        memory: 125Mi
    livenessProbe: 
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
    readinessProbe:
        initialDelaySeconds: 60
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
        successThreshold: 1
  additionalCatalogs:
    kafka: |-
      connector.name=kafka
      kafka.nodes=kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
      kafka.table-names=steadforce.tools
      kafka.hide-internal-columns=false
    iceberg: |-
      connector.name=iceberg
      iceberg.catalog.type=nessie
      iceberg.nessie-catalog.uri=http://nessie.nessie.svc.cluster.local:19120/api/v1
      iceberg.nessie-catalog.default-warehouse-dir=s3a://steadforce/iceberg
      iceberg.nessie-catalog.ref=main
      iceberg.register-table-procedure.enabled=true
      iceberg.file-format=PARQUET
      hive.s3.path-style-access=true
      hive.s3.endpoint=http://minio.minio.svc.cluster.local:80
      hive.s3.aws-access-key=${ENV:MINIO_ACCESS_KEY}
      hive.s3.aws-secret-key=${ENV:MINIO_SECRET_KEY}
      hive.s3.ssl.enabled=false
  env:
    - name: MINIO_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-cred-secret-mirror
          key: accesskey
    - name: MINIO_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: minio-cred-secret-mirror
          key: secretkey